# -*- coding: utf-8 -*-
"""Notebook5-Resuelta

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hFv_Qox-E9c0M6k5d356TpbcElzJ023a

# Programa Ingenias+ Data Science

Como dijimos en clases anteriores, Python tiene implementadas muchas librerias para poder trabajar con datos. En la clase de hoy trabajaremos con una de ellas: `Numpy`.

Antes de comenzar, vamos a hablar un poco de esta libreria o modulo.

**Numpy** es una librería optimizada para realizar cálculos numéricos con vectores y matrices. A diferencia de otros lenguajes de programación, Python no posee en su estructura central la figura de matrices. Eso quiere decir que para poder trabajar con esta estructura de datos deberiamos trabajar con listas de listas. NumPy introduce el concepto de arrays o matrices.

Al ser de código abierto, `numpy` posee una documentación muy amplia que es **SIEMPRE RECOMENDABLE** consultar.

- [Documentacion NumPy](https://devdocs.io/numpy/)

## Clase 4: Introduccion a NumPy

# Ejercicios

1. Crear un arreglo de ceros de longitud 12
2. Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
3. Crear un arreglo que tenga los números del 10 al 49
4. Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
5. Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
6. Calcular la media de un arreglo usando np.sum
7. Calcular la varianza de un arreglo usando np.sum y np.mean
8. Crear un array de números aleatorios usando np.random.randn.
"""

import numpy as np

# 1. Crear un arreglo de ceros de longitud 12.
EJ1 = np.zeros(12, dtype=int)
print ("EJERCICIO 1\n", EJ1)

# 2. Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5.
EJ2 = np.zeros(12, dtype=int)
EJ2[4]=10
print("EJERCICIO 2\n", EJ2)

# 3. Crear un arregle que tenga los números del 10 al 49.
EJ3 = np.arange(10, 50)
print("EJERCICIO 3\n", EJ3)

# 4. Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
EJ4 = np.arange(9).reshape(3, 3)
print("EJERCICIO 4\n", EJ4)

# 5. Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
EJ5 = (np.random.rand(100))
print("EJERCICIO 5\n", EJ5)
print("EJERCICIO 5 - MEDIA\n", np.mean(EJ5))
print("EJERCICIO 5 - VARIANZA\n", np.var(EJ5))

#¿¿HAY ALGUNA FORMA DE ESTABLECER QUE SEAN SIEMPRE LOS MISMOS NÚMEROS?? PARA QUE OTRA PERSONA AL CORRER EL CÓDIGO OBTENGA LOS MISMOS RESULTADOS

# 6. Calcular la media de un arreglo usando np.sum
EJ6 = media_sum = np.sum(EJ5)/ len(EJ5)
print("EJERCICIO 6 - MEDIA CON NP.SUM\n", EJ6)

# 7. Calcular la varianza de un arreglo usando np.sum y np.mean
MEDIA_EJ5 = np.mean(EJ5)
CALCULO_VARIANZA = np.sum((EJ5 - MEDIA_EJ5) ** 2) / len(EJ5)
print("EJERCICIO 7 - CALCULO VARIANZA \n", CALCULO_VARIANZA)

# 8. Crear un array de números aleatorios usando np.random.randn.
EJ8 = np.random.randn(15)
print("EJERCICIO 8\n", EJ8)